parameters:
 release_stage: Dev
 release_dependsOn: Build
 release_condition: |	
  and	
   (	
     succeeded(),	
     eq(variables['Build.SourceBranchName'], variables['releaseBranchName'])	
   )
 release_environment: dev
 release_appName: $(WebAppNameDev)
 
- stage: '${{ parameters.release_stage }}'
  displayName: 'Deploy to the ${{ parameters.release_stage }} environment'
  dependsOn: ${{ parameters.release_dependsOn }}
  condition: e${{ parameters.release_condition }}
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-18.04'
    environment: ${{ parameters.release_environment }}
    variables:
    - group: 'Release'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: 'Resource Manager - Tailspin - Space Game'
              appName: '${{ parameters.release_appName }}'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
